language: python
python:
    - "2.7"
    - "3.3"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script: "nosetests --with-coverage --cover-package=sheepdog"
after_success:
    - coveralls
