"""
Sheepdog
Copyright 2013 Adam Greig

Job file generation code.
"""

import inspect
from sheepdog.sheep import client

template = """#!{shebang}
{geopts}

# Sheepdog Job File
# Autogenerated by Sheepdog. Don't edit by hand.

###########################################################
## Clientside code from Sheepdog:

{client_code}

##
###########################################################

Client("{url}", {request_id}, {job_index}).go()
"""

default_shebang = "/usr/bin/env python3"

def job_file(url, request_id, job_index, grid_engine_opts=None,
             shebang=default_shebang):
    if grid_engine_opts is None:
        grid_engine_opts = []
    geopts = '\n'.join("#$ {0}".format(opt) for opt in grid_engine_opts)
    client_code = inspect.getsource(client)
    return template.format(**locals())
